spring.application.name=review-processor

# Kafka Consumer Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=review-processor-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.dotohtwo.review_processor.model.Review
spring.kafka.consumer.properties.spring.json.trusted.packages=com.dotohtwo.review_processor.model

# Topic name
kafka.topic.reviews=reviews

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Follower service
follower-service.base-url=http://localhost:8080
